[project]
name = "embeddings-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.12.3",
    "debugpy==1.8.12",
    "fastparquet==2024.11.0",
    "hydra-core==1.3.2",
    "jupyter==1.1.1",
    "lxml==5.3.0",
    "matplotlib==3.9.3",
    "metaflow==2.13.2",
    "omegaconf==2.3.0",
    "pyarrow==18.1.0",
    "pytest==8.3.4",
    "python-dotenv==1.0.1",
    "snakeviz==2.2.2",
    "torch==2.5.1",
    "tqdm==4.67.0",
    "utils",
    "wikiparser",
]

[tool.pytest.ini_options]
pythonpath = "src"

[tool.uv.sources]
wikiparser = { path = "../wikiparser", editable = true }
utils = { path = "../utils", editable = true }
