[tool.poetry]
name = "embeddings-comparison"
version = "0.1.0"
description = "Package for comparing embeddings"
authors = ["Andrey Pigarev <pigarev.a.g2014@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
