[tool.poetry]
name = "utils"
version = "0.1.0"
description = "Package with different helper functions"
authors = ["Andrey Pigarev <pigarev.a.g2014@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "*", from="src"}]

[tool.poetry.dependencies]
python = "^3.12"
sentence-transformers = "3.2.1"
openai = "1.56.2"
numpy = "2.2.1"
faiss-cpu = "1.9.0"
tiktoken = "0.8.0"
pandas = "2.2.3"

[tool.poetry.group.dev.dependencies]
mypy = "1.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
